language: node_js
node_js:
- "10.15.0"
branches:
 only:
 - master
before_script:
- npm install -g ionic cordova
script:
- ionic cordova build browser --prod --release
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: platforms/browser/www